[package]
name = "tg-parser"
edition = "2024"
version.workspace = true

[dependencies]
varint-rs.workspace = true
anyhow.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
base64.workspace = true

tg-bytes-util.workspace = true
